### ISSUE TITLE
"Video Number" on Prime Guardian and Other Weapons

### ISSUE THREAD

**Issue by sivelswhy** [SoloUnity/Valorant-Store-Checker-App#5]
Hello,
I don't think that's normal but here's my problem :
On the [prime guardian](https://valorantstore.net/skin/2a049f35-4bcd-af25-21fd-ec942e2d5007) and other weapons that i tested on, there is a text which is written "Video number" just before the skin level **or** the variant. When clicking on it, nothing occurs.
I have the app on the latest release available on the App Store **_(1.2.6)_**

Here are screenshots for you to see. If you need any more info about that, I'm open !

![Image](https://user-images.githubusercontent.com/82051273/189952291-29cd62e8-85bd-46ba-9b44-dd47477c1751.png)
![image](https://user-images.githubusercontent.com/82051273/189952302-b88a1bf7-68cf-4908-bdb8-234aa706d2c0.png)

**Comment by SoloUnity** [comment]
Hi!
This is a visual bug brought on by a change in the behaviour of menus in iOS 16. I'll be sure to fix it in the next update! Thanks for reporting it!
